### ISSUE TITLE
SPT_Alarms missing .tmc files

### ISSUE THREAD

**Issue by vanoo1983** [Beckhoff-USA-Community/SPT_Samples#1]
Hello

Thank you for the example projects.

I wanted to look at the SPT_Alarms project because we would also like to change the severity of a message without creating the event multiple times.

I noticed that the tmc files (ComponentEvents, EquipmentEvents, MachineEvents) are missing in SPT_Alarms.

**Comment by mcclureTC** [comment]
Thank you for reporting, the tmc files have been added.
